version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-deploy:
    working_directory: ~/seppuku-sudoku/frontend
    executor:
      name: node/default
      tag: "14.17"
    steps:
      - checkout:
          path: ~/seppuku-sudoku
      - node/with-cache:
          cache-version: v2
          dir: ~/seppuku-sudoku/frontend/node_modules
          steps:
            - run: yarn install
      - run: yarn build
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  deploy:
    jobs:
      - build-deploy:
          context: Firebase